version: '2'

services:
  postgres:
    image: postgres:9.6
    ports:
    - 5432:5432
    volumes:
    - /tictactoe/db:/var/lib/postgresql/data

  redis:
    image: redis:4.0.11
    ports:
      - 6379:6379
